language: cpp
sudo: false
os: linux

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - CC=gcc-5
        - CXX=g++-5
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CC=gcc-6
        - CXX=g++-6
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7

before_install:
  - sudo apt-get update
  # Vulkan dependencies
  - sudo apt-get install libglm-dev cmake libxcb-dri3-0 libxcb-present0 libpciaccess0 libpng-dev libxcb-keysyms1-dev libxcb-dri3-dev libx11-dev libmirclient-dev libwayland-dev libxrandr-dev
  # GLFW dependencies
  - sudo apt-get install xorg-dev
  # LunarG SDK
  - cd /tmp
  - wget https://sdk.lunarg.com/sdk/download/1.1.77.0/linux/vulkansdk-linux-x86_64-1.1.77.0.tar.gz
  - cd ~
  - mkdir vulkan
  - cd vulkan
  - tar zxf /tmp/vulkansdk-linux-x86_64-1.1.77.0.tar.gz
  - source ~/vulkan/1.1.77.0/setup-env.sh

before_script:
  - cd "$TRAVIS_BUILD_DIR"
  - mkdir build
  - cd build
  - cmake ..
  - cd ..

script:
  - cd build
  - make
