language: cpp
sudo: false
os: linux

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - CC=gcc-5
        - CXX=g++-5
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CC=gcc-6
        - CXX=g++-6
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7

before_script:
  # LunarG SDK
  - cd /tmp
  - wget https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.1.77.0/linux/vulkansdk-linux-x86_64-1.1.77.0.tar.gz
  - cd ~
  - mkdir vulkan
  - cd vulkan
  - tar zxf /tmp/vulkansdk-linux-x86_64-1.1.77.0.tar.gz
  - source ~/vulkan/1.1.77.0/setup-env.sh

  - mkdir build
  - cd build
  - cmake ..
  - cd ..

script:
  - cd build
  - make
